// Code generated by entc, DO NOT EDIT.

package manga

const (
	// Label holds the string label denoting the manga type in the database.
	Label = "manga"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMangaID holds the string denoting the mangaid field in the database.
	FieldMangaID = "manga_id"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldMapping holds the string denoting the mapping field in the database.
	FieldMapping = "mapping"
	// EdgeChapters holds the string denoting the chapters edge name in mutations.
	EdgeChapters = "Chapters"
	// Table holds the table name of the manga in the database.
	Table = "mangas"
	// ChaptersTable is the table that holds the Chapters relation/edge.
	ChaptersTable = "chapters"
	// ChaptersInverseTable is the table name for the Chapter entity.
	// It exists in this package in order to avoid circular dependency with the "chapter" package.
	ChaptersInverseTable = "chapters"
	// ChaptersColumn is the table column denoting the Chapters relation/edge.
	ChaptersColumn = "manga_chapters"
)

// Columns holds all SQL columns for manga fields.
var Columns = []string{
	FieldID,
	FieldMangaID,
	FieldSource,
	FieldTitle,
	FieldMapping,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
