// Code generated by entc, DO NOT EDIT.

package manga

const (
	// Label holds the string label denoting the manga type in the database.
	Label = "manga"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMangaID holds the string denoting the mangaid field in the database.
	FieldMangaID = "manga_id"
	// FieldPlugin holds the string denoting the plugin field in the database.
	FieldPlugin = "plugin"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// EdgeChapters holds the string denoting the chapters edge name in mutations.
	EdgeChapters = "chapters"
	// Table holds the table name of the manga in the database.
	Table = "mangas"
	// ChaptersTable is the table that holds the chapters relation/edge.
	ChaptersTable = "chapters"
	// ChaptersInverseTable is the table name for the Chapter entity.
	// It exists in this package in order to avoid circular dependency with the "chapter" package.
	ChaptersInverseTable = "chapters"
	// ChaptersColumn is the table column denoting the chapters relation/edge.
	ChaptersColumn = "manga_chapters"
)

// Columns holds all SQL columns for manga fields.
var Columns = []string{
	FieldID,
	FieldMangaID,
	FieldPlugin,
	FieldTitle,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
