// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: internal/sources/mangaplus/proto/mangaplus.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Language int32

const (
	Language_ENGLISH       Language = 0
	Language_SPANISH       Language = 1
	Language_FRENCH        Language = 2
	Language_INDONESIAN    Language = 3
	Language_PORTUGUESE_BR Language = 4
	Language_RUSSIAN       Language = 5
	Language_THAI          Language = 6
)

// Enum value maps for Language.
var (
	Language_name = map[int32]string{
		0: "ENGLISH",
		1: "SPANISH",
		2: "FRENCH",
		3: "INDONESIAN",
		4: "PORTUGUESE_BR",
		5: "RUSSIAN",
		6: "THAI",
	}
	Language_value = map[string]int32{
		"ENGLISH":       0,
		"SPANISH":       1,
		"FRENCH":        2,
		"INDONESIAN":    3,
		"PORTUGUESE_BR": 4,
		"RUSSIAN":       5,
		"THAI":          6,
	}
)

func (x Language) Enum() *Language {
	p := new(Language)
	*p = x
	return p
}

func (x Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Language) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_sources_mangaplus_proto_mangaplus_proto_enumTypes[0].Descriptor()
}

func (Language) Type() protoreflect.EnumType {
	return &file_internal_sources_mangaplus_proto_mangaplus_proto_enumTypes[0]
}

func (x Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Language.Descriptor instead.
func (Language) EnumDescriptor() ([]byte, []int) {
	return file_internal_sources_mangaplus_proto_mangaplus_proto_rawDescGZIP(), []int{0}
}

type Title struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TitleId       uint32                 `protobuf:"varint,1,opt,name=title_id,json=titleId,proto3" json:"title_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Language      Language               `protobuf:"varint,7,opt,name=language,proto3,enum=mangaplus.Language" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Title) Reset() {
	*x = Title{}
	mi := &file_internal_sources_mangaplus_proto_mangaplus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Title) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Title) ProtoMessage() {}

func (x *Title) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sources_mangaplus_proto_mangaplus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Title.ProtoReflect.Descriptor instead.
func (*Title) Descriptor() ([]byte, []int) {
	return file_internal_sources_mangaplus_proto_mangaplus_proto_rawDescGZIP(), []int{0}
}

func (x *Title) GetTitleId() uint32 {
	if x != nil {
		return x.TitleId
	}
	return 0
}

func (x *Title) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Title) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_ENGLISH
}

type AllTitlesGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TheTitle      string                 `protobuf:"bytes,1,opt,name=the_title,json=theTitle,proto3" json:"the_title,omitempty"`
	Titles        []*Title               `protobuf:"bytes,2,rep,name=titles,proto3" json:"titles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllTitlesGroup) Reset() {
	*x = AllTitlesGroup{}
	mi := &file_internal_sources_mangaplus_proto_mangaplus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllTitlesGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllTitlesGroup) ProtoMessage() {}

func (x *AllTitlesGroup) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sources_mangaplus_proto_mangaplus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllTitlesGroup.ProtoReflect.Descriptor instead.
func (*AllTitlesGroup) Descriptor() ([]byte, []int) {
	return file_internal_sources_mangaplus_proto_mangaplus_proto_rawDescGZIP(), []int{1}
}

func (x *AllTitlesGroup) GetTheTitle() string {
	if x != nil {
		return x.TheTitle
	}
	return ""
}

func (x *AllTitlesGroup) GetTitles() []*Title {
	if x != nil {
		return x.Titles
	}
	return nil
}

type AllTitlesViewV2 struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AllTitlesGroup []*AllTitlesGroup      `protobuf:"bytes,1,rep,name=all_titles_group,json=allTitlesGroup,proto3" json:"all_titles_group,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AllTitlesViewV2) Reset() {
	*x = AllTitlesViewV2{}
	mi := &file_internal_sources_mangaplus_proto_mangaplus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllTitlesViewV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllTitlesViewV2) ProtoMessage() {}

func (x *AllTitlesViewV2) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sources_mangaplus_proto_mangaplus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllTitlesViewV2.ProtoReflect.Descriptor instead.
func (*AllTitlesViewV2) Descriptor() ([]byte, []int) {
	return file_internal_sources_mangaplus_proto_mangaplus_proto_rawDescGZIP(), []int{2}
}

func (x *AllTitlesViewV2) GetAllTitlesGroup() []*AllTitlesGroup {
	if x != nil {
		return x.AllTitlesGroup
	}
	return nil
}

type Chapter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TitleId       uint32                 `protobuf:"varint,1,opt,name=title_id,json=titleId,proto3" json:"title_id,omitempty"`
	ChapterId     uint32                 `protobuf:"varint,2,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SubTitle      string                 `protobuf:"bytes,4,opt,name=sub_title,json=subTitle,proto3" json:"sub_title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chapter) Reset() {
	*x = Chapter{}
	mi := &file_internal_sources_mangaplus_proto_mangaplus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chapter) ProtoMessage() {}

func (x *Chapter) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sources_mangaplus_proto_mangaplus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chapter.ProtoReflect.Descriptor instead.
func (*Chapter) Descriptor() ([]byte, []int) {
	return file_internal_sources_mangaplus_proto_mangaplus_proto_rawDescGZIP(), []int{3}
}

func (x *Chapter) GetTitleId() uint32 {
	if x != nil {
		return x.TitleId
	}
	return 0
}

func (x *Chapter) GetChapterId() uint32 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

func (x *Chapter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Chapter) GetSubTitle() string {
	if x != nil {
		return x.SubTitle
	}
	return ""
}

type ChapterBlock struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FirstChapterList []*Chapter             `protobuf:"bytes,2,rep,name=first_chapter_list,json=firstChapterList,proto3" json:"first_chapter_list,omitempty"`
	LastChapterList  []*Chapter             `protobuf:"bytes,4,rep,name=last_chapter_list,json=lastChapterList,proto3" json:"last_chapter_list,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChapterBlock) Reset() {
	*x = ChapterBlock{}
	mi := &file_internal_sources_mangaplus_proto_mangaplus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterBlock) ProtoMessage() {}

func (x *ChapterBlock) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sources_mangaplus_proto_mangaplus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterBlock.ProtoReflect.Descriptor instead.
func (*ChapterBlock) Descriptor() ([]byte, []int) {
	return file_internal_sources_mangaplus_proto_mangaplus_proto_rawDescGZIP(), []int{4}
}

func (x *ChapterBlock) GetFirstChapterList() []*Chapter {
	if x != nil {
		return x.FirstChapterList
	}
	return nil
}

func (x *ChapterBlock) GetLastChapterList() []*Chapter {
	if x != nil {
		return x.LastChapterList
	}
	return nil
}

type TitleDetailView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         *Title                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Chapters      []*ChapterBlock        `protobuf:"bytes,28,rep,name=chapters,proto3" json:"chapters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TitleDetailView) Reset() {
	*x = TitleDetailView{}
	mi := &file_internal_sources_mangaplus_proto_mangaplus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TitleDetailView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitleDetailView) ProtoMessage() {}

func (x *TitleDetailView) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sources_mangaplus_proto_mangaplus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitleDetailView.ProtoReflect.Descriptor instead.
func (*TitleDetailView) Descriptor() ([]byte, []int) {
	return file_internal_sources_mangaplus_proto_mangaplus_proto_rawDescGZIP(), []int{5}
}

func (x *TitleDetailView) GetTitle() *Title {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *TitleDetailView) GetChapters() []*ChapterBlock {
	if x != nil {
		return x.Chapters
	}
	return nil
}

type MangaPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUrl      string                 `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Width         uint32                 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	EncryptionKey string                 `protobuf:"bytes,5,opt,name=encryption_key,json=encryptionKey,proto3" json:"encryption_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaPage) Reset() {
	*x = MangaPage{}
	mi := &file_internal_sources_mangaplus_proto_mangaplus_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaPage) ProtoMessage() {}

func (x *MangaPage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sources_mangaplus_proto_mangaplus_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaPage.ProtoReflect.Descriptor instead.
func (*MangaPage) Descriptor() ([]byte, []int) {
	return file_internal_sources_mangaplus_proto_mangaplus_proto_rawDescGZIP(), []int{6}
}

func (x *MangaPage) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *MangaPage) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MangaPage) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MangaPage) GetEncryptionKey() string {
	if x != nil {
		return x.EncryptionKey
	}
	return ""
}

type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *MangaPage             `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_internal_sources_mangaplus_proto_mangaplus_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sources_mangaplus_proto_mangaplus_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_internal_sources_mangaplus_proto_mangaplus_proto_rawDescGZIP(), []int{7}
}

func (x *Page) GetPage() *MangaPage {
	if x != nil {
		return x.Page
	}
	return nil
}

type MangaViewer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pages         []*Page                `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaViewer) Reset() {
	*x = MangaViewer{}
	mi := &file_internal_sources_mangaplus_proto_mangaplus_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaViewer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaViewer) ProtoMessage() {}

func (x *MangaViewer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sources_mangaplus_proto_mangaplus_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaViewer.ProtoReflect.Descriptor instead.
func (*MangaViewer) Descriptor() ([]byte, []int) {
	return file_internal_sources_mangaplus_proto_mangaplus_proto_rawDescGZIP(), []int{8}
}

func (x *MangaViewer) GetPages() []*Page {
	if x != nil {
		return x.Pages
	}
	return nil
}

type SuccessResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IsFeaturedUpdated bool                   `protobuf:"varint,1,opt,name=is_featured_updated,json=isFeaturedUpdated,proto3" json:"is_featured_updated,omitempty"`
	TitleDetailView   *TitleDetailView       `protobuf:"bytes,8,opt,name=title_detail_view,json=titleDetailView,proto3" json:"title_detail_view,omitempty"`
	MangaViewer       *MangaViewer           `protobuf:"bytes,10,opt,name=manga_viewer,json=mangaViewer,proto3" json:"manga_viewer,omitempty"`
	AllTitlesViewV2   *AllTitlesViewV2       `protobuf:"bytes,25,opt,name=all_titles_view_v2,json=allTitlesViewV2,proto3" json:"all_titles_view_v2,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SuccessResult) Reset() {
	*x = SuccessResult{}
	mi := &file_internal_sources_mangaplus_proto_mangaplus_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessResult) ProtoMessage() {}

func (x *SuccessResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sources_mangaplus_proto_mangaplus_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessResult.ProtoReflect.Descriptor instead.
func (*SuccessResult) Descriptor() ([]byte, []int) {
	return file_internal_sources_mangaplus_proto_mangaplus_proto_rawDescGZIP(), []int{9}
}

func (x *SuccessResult) GetIsFeaturedUpdated() bool {
	if x != nil {
		return x.IsFeaturedUpdated
	}
	return false
}

func (x *SuccessResult) GetTitleDetailView() *TitleDetailView {
	if x != nil {
		return x.TitleDetailView
	}
	return nil
}

func (x *SuccessResult) GetMangaViewer() *MangaViewer {
	if x != nil {
		return x.MangaViewer
	}
	return nil
}

func (x *SuccessResult) GetAllTitlesViewV2() *AllTitlesViewV2 {
	if x != nil {
		return x.AllTitlesViewV2
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *SuccessResult         `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_internal_sources_mangaplus_proto_mangaplus_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sources_mangaplus_proto_mangaplus_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_internal_sources_mangaplus_proto_mangaplus_proto_rawDescGZIP(), []int{10}
}

func (x *Response) GetSuccess() *SuccessResult {
	if x != nil {
		return x.Success
	}
	return nil
}

var File_internal_sources_mangaplus_proto_mangaplus_proto protoreflect.FileDescriptor

const file_internal_sources_mangaplus_proto_mangaplus_proto_rawDesc = "" +
	"\n" +
	"0internal/sources/mangaplus/proto/mangaplus.proto\x12\tmangaplus\"g\n" +
	"\x05Title\x12\x19\n" +
	"\btitle_id\x18\x01 \x01(\rR\atitleId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12/\n" +
	"\blanguage\x18\a \x01(\x0e2\x13.mangaplus.LanguageR\blanguage\"W\n" +
	"\x0eAllTitlesGroup\x12\x1b\n" +
	"\tthe_title\x18\x01 \x01(\tR\btheTitle\x12(\n" +
	"\x06titles\x18\x02 \x03(\v2\x10.mangaplus.TitleR\x06titles\"V\n" +
	"\x0fAllTitlesViewV2\x12C\n" +
	"\x10all_titles_group\x18\x01 \x03(\v2\x19.mangaplus.AllTitlesGroupR\x0eallTitlesGroup\"t\n" +
	"\aChapter\x12\x19\n" +
	"\btitle_id\x18\x01 \x01(\rR\atitleId\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x02 \x01(\rR\tchapterId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tsub_title\x18\x04 \x01(\tR\bsubTitle\"\x90\x01\n" +
	"\fChapterBlock\x12@\n" +
	"\x12first_chapter_list\x18\x02 \x03(\v2\x12.mangaplus.ChapterR\x10firstChapterList\x12>\n" +
	"\x11last_chapter_list\x18\x04 \x03(\v2\x12.mangaplus.ChapterR\x0flastChapterList\"n\n" +
	"\x0fTitleDetailView\x12&\n" +
	"\x05title\x18\x01 \x01(\v2\x10.mangaplus.TitleR\x05title\x123\n" +
	"\bchapters\x18\x1c \x03(\v2\x17.mangaplus.ChapterBlockR\bchapters\"}\n" +
	"\tMangaPage\x12\x1b\n" +
	"\timage_url\x18\x01 \x01(\tR\bimageUrl\x12\x14\n" +
	"\x05width\x18\x02 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\rR\x06height\x12%\n" +
	"\x0eencryption_key\x18\x05 \x01(\tR\rencryptionKey\"0\n" +
	"\x04Page\x12(\n" +
	"\x04page\x18\x01 \x01(\v2\x14.mangaplus.MangaPageR\x04page\"4\n" +
	"\vMangaViewer\x12%\n" +
	"\x05pages\x18\x01 \x03(\v2\x0f.mangaplus.PageR\x05pages\"\x8b\x02\n" +
	"\rSuccessResult\x12.\n" +
	"\x13is_featured_updated\x18\x01 \x01(\bR\x11isFeaturedUpdated\x12F\n" +
	"\x11title_detail_view\x18\b \x01(\v2\x1a.mangaplus.TitleDetailViewR\x0ftitleDetailView\x129\n" +
	"\fmanga_viewer\x18\n" +
	" \x01(\v2\x16.mangaplus.MangaViewerR\vmangaViewer\x12G\n" +
	"\x12all_titles_view_v2\x18\x19 \x01(\v2\x1a.mangaplus.AllTitlesViewV2R\x0fallTitlesViewV2\">\n" +
	"\bResponse\x122\n" +
	"\asuccess\x18\x01 \x01(\v2\x18.mangaplus.SuccessResultR\asuccess*j\n" +
	"\bLanguage\x12\v\n" +
	"\aENGLISH\x10\x00\x12\v\n" +
	"\aSPANISH\x10\x01\x12\n" +
	"\n" +
	"\x06FRENCH\x10\x02\x12\x0e\n" +
	"\n" +
	"INDONESIAN\x10\x03\x12\x11\n" +
	"\rPORTUGUESE_BR\x10\x04\x12\v\n" +
	"\aRUSSIAN\x10\x05\x12\b\n" +
	"\x04THAI\x10\x06BFZDgithub.com/browningluke/mangathr/v2/internal/sources/mangaplus/protob\x06proto3"

var (
	file_internal_sources_mangaplus_proto_mangaplus_proto_rawDescOnce sync.Once
	file_internal_sources_mangaplus_proto_mangaplus_proto_rawDescData []byte
)

func file_internal_sources_mangaplus_proto_mangaplus_proto_rawDescGZIP() []byte {
	file_internal_sources_mangaplus_proto_mangaplus_proto_rawDescOnce.Do(func() {
		file_internal_sources_mangaplus_proto_mangaplus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_sources_mangaplus_proto_mangaplus_proto_rawDesc), len(file_internal_sources_mangaplus_proto_mangaplus_proto_rawDesc)))
	})
	return file_internal_sources_mangaplus_proto_mangaplus_proto_rawDescData
}

var file_internal_sources_mangaplus_proto_mangaplus_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_sources_mangaplus_proto_mangaplus_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_sources_mangaplus_proto_mangaplus_proto_goTypes = []any{
	(Language)(0),           // 0: mangaplus.Language
	(*Title)(nil),           // 1: mangaplus.Title
	(*AllTitlesGroup)(nil),  // 2: mangaplus.AllTitlesGroup
	(*AllTitlesViewV2)(nil), // 3: mangaplus.AllTitlesViewV2
	(*Chapter)(nil),         // 4: mangaplus.Chapter
	(*ChapterBlock)(nil),    // 5: mangaplus.ChapterBlock
	(*TitleDetailView)(nil), // 6: mangaplus.TitleDetailView
	(*MangaPage)(nil),       // 7: mangaplus.MangaPage
	(*Page)(nil),            // 8: mangaplus.Page
	(*MangaViewer)(nil),     // 9: mangaplus.MangaViewer
	(*SuccessResult)(nil),   // 10: mangaplus.SuccessResult
	(*Response)(nil),        // 11: mangaplus.Response
}
var file_internal_sources_mangaplus_proto_mangaplus_proto_depIdxs = []int32{
	0,  // 0: mangaplus.Title.language:type_name -> mangaplus.Language
	1,  // 1: mangaplus.AllTitlesGroup.titles:type_name -> mangaplus.Title
	2,  // 2: mangaplus.AllTitlesViewV2.all_titles_group:type_name -> mangaplus.AllTitlesGroup
	4,  // 3: mangaplus.ChapterBlock.first_chapter_list:type_name -> mangaplus.Chapter
	4,  // 4: mangaplus.ChapterBlock.last_chapter_list:type_name -> mangaplus.Chapter
	1,  // 5: mangaplus.TitleDetailView.title:type_name -> mangaplus.Title
	5,  // 6: mangaplus.TitleDetailView.chapters:type_name -> mangaplus.ChapterBlock
	7,  // 7: mangaplus.Page.page:type_name -> mangaplus.MangaPage
	8,  // 8: mangaplus.MangaViewer.pages:type_name -> mangaplus.Page
	6,  // 9: mangaplus.SuccessResult.title_detail_view:type_name -> mangaplus.TitleDetailView
	9,  // 10: mangaplus.SuccessResult.manga_viewer:type_name -> mangaplus.MangaViewer
	3,  // 11: mangaplus.SuccessResult.all_titles_view_v2:type_name -> mangaplus.AllTitlesViewV2
	10, // 12: mangaplus.Response.success:type_name -> mangaplus.SuccessResult
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_internal_sources_mangaplus_proto_mangaplus_proto_init() }
func file_internal_sources_mangaplus_proto_mangaplus_proto_init() {
	if File_internal_sources_mangaplus_proto_mangaplus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_sources_mangaplus_proto_mangaplus_proto_rawDesc), len(file_internal_sources_mangaplus_proto_mangaplus_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_sources_mangaplus_proto_mangaplus_proto_goTypes,
		DependencyIndexes: file_internal_sources_mangaplus_proto_mangaplus_proto_depIdxs,
		EnumInfos:         file_internal_sources_mangaplus_proto_mangaplus_proto_enumTypes,
		MessageInfos:      file_internal_sources_mangaplus_proto_mangaplus_proto_msgTypes,
	}.Build()
	File_internal_sources_mangaplus_proto_mangaplus_proto = out.File
	file_internal_sources_mangaplus_proto_mangaplus_proto_goTypes = nil
	file_internal_sources_mangaplus_proto_mangaplus_proto_depIdxs = nil
}
