---
database:
  driver: "sqlite"
  uri: "./examples/database.sqlite"
metadata:
  agent: "comicinfo"
  location: "internal"
downloader:
  simultaneousPages: 5
  pageRetries: 5
  delay:
    page: 100
    chapter: 200
    updateChapter: 2000
  output:
    path: ''
    updatePath: ''
    zip: true
    filenameTemplate: "{num:3} - Chapter {num}{? - {title}}" # Set a global template
    # syntax is in format:
    # {num:3} = number padded to 3 digits (e.g. 001, 010, 100, 1000)
    # {num}   = number with no padding (e.g. 1, 10, 100, 1000)
    # {?xx - {title} - xx}  = if title is not "", replace with xx-title-xx, else use ""
sources:
  mangadex:
    syncDeletions: false
    filenameTemplate: "{num:3} - Chapter {num}{? - {title}}" # Set specific for source (overrides global)
    ratingFitler: ["safe", "suggestive", "erotica"]
    dataSaver: false