---
logLevel: "INFO"
database:
  driver: postgres
  createDatabase: false
  autoMigrate: true
  sqlite:
    path: ~/mangathr/db.sqlite
  postgres:
    host: 127.0.0.1
    port: 5432
    user: mangathr
    password: PASSWORD
    dbName: mangathr
    sslMode: disable
    opts: ''
downloader:
  dryRun: false
  cleanupOnError: true
  simultaneousPages: 2
  pageRetries: 5
  delay:
    page: "100ms"
    chapter: "200ms"
    updateChapter: "2s"
  output:
    path: './downloads'
    updatePath: './downloads-update'
    zip: true
    filenameTemplate: "{num:3} - Chapter {num}{lang: - <.>}{title: - <.>}{groups: [<.>]}" # Set a global template
  metadata:
    agent: "comicinfo"
    location: "internal"
sources:
  mangadex:
    syncDeletions: false
    filenameTemplate: "{num:3} - Chapter {num}{title: - <.>}{groups: [<.>]} (mangadex)" # Set specific for source (overrides global)
    ratingFilter: ["safe", "suggestive", "erotica"]
    languageFilter: ["en"] # , "fr"
    dataSaver: false
    groups:
      # Only download chapters from <Example A> and <Example B>
      # include:
        # - "Example A"
        # - "Example B"
      # Do not download chapters from <Example C>
      exclude:
        - "Example C"
  cubari:
    filenameTemplate: "{num:4} - Chapter {num:2}{title: - <.>}{groups: {<.>}}" # Set specific for source (overrides global)
    groups:
      # Only download chapters from <Example A> and <Example B>
      # include:
      # - "Example A"
      # - "Example B"
      # Do not download chapters from <Example C>
      exclude:
        - "Example C"
