---
logLevel: "INFO"
database:
  driver: "sqlite"
  uri: "./examples/database.sqlite"
downloader:
  simultaneousPages: 2
  pageRetries: 5
  delay:
    page: "100ms"
    chapter: "200ms"
    updateChapter: "2s"
  output:
    path: './downloads'
    updatePath: ''
    zip: true
    filenameTemplate: "{num:3} - Chapter {num}{? - {lang}}{? - {title}}" # Set a global template
    # syntax is in format:
    # {num:3} = number padded to 3 digits (e.g. 001, 010, 100, 1000)
    # {num}   = number with no padding (e.g. 1, 10, 100, 1000)
    # {?xx - {title} - xx}  = if title is not "", replace with xx-title-xx, else use ""
  metadata:
    agent: "comicinfo"
    location: "internal"
sources:
  mangadex:
    syncDeletions: false
    filenameTemplate: "{num:3} - Chapter {num}{? - {lang}}{? - {title}}" # Set specific for source (overrides global)
    ratingFilter: ["safe", "suggestive", "erotica"]
    languageFilter: ["en"] # , "fr"
    dataSaver: false