---
logLevel: "INFO"
database:
  driver: "sqlite"
  uri: "examples/db.sqlite"
downloader:
  dryRun: false
  simultaneousPages: 2
  pageRetries: 5
  delay:
    page: "100ms"
    chapter: "200ms"
    updateChapter: "2s"
  output:
    path: './downloads'
    updatePath: './downloads-update'
    zip: true
    filenameTemplate: "{num:3} - Chapter {num}{lang: - <.>}{title: - <.>}{groups: [<.>]}" # Set a global template
  metadata:
    agent: "comicinfo"
    location: "internal"
sources:
  mangadex:
    syncDeletions: false
    filenameTemplate: "{num:3} - Chapter {num}{title: - <.>}{groups: [<.>]} (mangadex)" # Set specific for source (overrides global)
    ratingFilter: ["safe", "suggestive", "erotica"]
    languageFilter: ["en"] # , "fr"
    dataSaver: false
