// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/browningluke/mangathr/ent/chapter"
	"github.com/browningluke/mangathr/ent/manga"
	"github.com/browningluke/mangathr/ent/predicate"
)

// MangaQuery is the builder for querying Manga entities.
type MangaQuery struct {
	config
	ctx          *QueryContext
	order        []OrderFunc
	inters       []Interceptor
	predicates   []predicate.Manga
	withChapters *ChapterQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MangaQuery builder.
func (mq *MangaQuery) Where(ps ...predicate.Manga) *MangaQuery {
	mq.predicates = append(mq.predicates, ps...)
	return mq
}

// Limit the number of records to be returned by this query.
func (mq *MangaQuery) Limit(limit int) *MangaQuery {
	mq.ctx.Limit = &limit
	return mq
}

// Offset to start from.
func (mq *MangaQuery) Offset(offset int) *MangaQuery {
	mq.ctx.Offset = &offset
	return mq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mq *MangaQuery) Unique(unique bool) *MangaQuery {
	mq.ctx.Unique = &unique
	return mq
}

// Order specifies how the records should be ordered.
func (mq *MangaQuery) Order(o ...OrderFunc) *MangaQuery {
	mq.order = append(mq.order, o...)
	return mq
}

// QueryChapters chains the current query on the "Chapters" edge.
func (mq *MangaQuery) QueryChapters() *ChapterQuery {
	query := (&ChapterClient{config: mq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(manga.Table, manga.FieldID, selector),
			sqlgraph.To(chapter.Table, chapter.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, manga.ChaptersTable, manga.ChaptersColumn),
		)
		fromU = sqlgraph.SetNeighbors(mq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Manga entity from the query.
// Returns a *NotFoundError when no Manga was found.
func (mq *MangaQuery) First(ctx context.Context) (*Manga, error) {
	nodes, err := mq.Limit(1).All(setContextOp(ctx, mq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{manga.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mq *MangaQuery) FirstX(ctx context.Context) *Manga {
	node, err := mq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Manga ID from the query.
// Returns a *NotFoundError when no Manga ID was found.
func (mq *MangaQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mq.Limit(1).IDs(setContextOp(ctx, mq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{manga.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mq *MangaQuery) FirstIDX(ctx context.Context) int {
	id, err := mq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Manga entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Manga entity is found.
// Returns a *NotFoundError when no Manga entities are found.
func (mq *MangaQuery) Only(ctx context.Context) (*Manga, error) {
	nodes, err := mq.Limit(2).All(setContextOp(ctx, mq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{manga.Label}
	default:
		return nil, &NotSingularError{manga.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mq *MangaQuery) OnlyX(ctx context.Context) *Manga {
	node, err := mq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Manga ID in the query.
// Returns a *NotSingularError when more than one Manga ID is found.
// Returns a *NotFoundError when no entities are found.
func (mq *MangaQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mq.Limit(2).IDs(setContextOp(ctx, mq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{manga.Label}
	default:
		err = &NotSingularError{manga.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mq *MangaQuery) OnlyIDX(ctx context.Context) int {
	id, err := mq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Mangas.
func (mq *MangaQuery) All(ctx context.Context) ([]*Manga, error) {
	ctx = setContextOp(ctx, mq.ctx, "All")
	if err := mq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Manga, *MangaQuery]()
	return withInterceptors[[]*Manga](ctx, mq, qr, mq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mq *MangaQuery) AllX(ctx context.Context) []*Manga {
	nodes, err := mq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Manga IDs.
func (mq *MangaQuery) IDs(ctx context.Context) (ids []int, err error) {
	if mq.ctx.Unique == nil && mq.path != nil {
		mq.Unique(true)
	}
	ctx = setContextOp(ctx, mq.ctx, "IDs")
	if err = mq.Select(manga.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mq *MangaQuery) IDsX(ctx context.Context) []int {
	ids, err := mq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mq *MangaQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mq.ctx, "Count")
	if err := mq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mq, querierCount[*MangaQuery](), mq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mq *MangaQuery) CountX(ctx context.Context) int {
	count, err := mq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mq *MangaQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mq.ctx, "Exist")
	switch _, err := mq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mq *MangaQuery) ExistX(ctx context.Context) bool {
	exist, err := mq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MangaQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mq *MangaQuery) Clone() *MangaQuery {
	if mq == nil {
		return nil
	}
	return &MangaQuery{
		config:       mq.config,
		ctx:          mq.ctx.Clone(),
		order:        append([]OrderFunc{}, mq.order...),
		inters:       append([]Interceptor{}, mq.inters...),
		predicates:   append([]predicate.Manga{}, mq.predicates...),
		withChapters: mq.withChapters.Clone(),
		// clone intermediate query.
		sql:  mq.sql.Clone(),
		path: mq.path,
	}
}

// WithChapters tells the query-builder to eager-load the nodes that are connected to
// the "Chapters" edge. The optional arguments are used to configure the query builder of the edge.
func (mq *MangaQuery) WithChapters(opts ...func(*ChapterQuery)) *MangaQuery {
	query := (&ChapterClient{config: mq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mq.withChapters = query
	return mq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MangaID string `json:"MangaID,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Manga.Query().
//		GroupBy(manga.FieldMangaID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mq *MangaQuery) GroupBy(field string, fields ...string) *MangaGroupBy {
	mq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MangaGroupBy{build: mq}
	grbuild.flds = &mq.ctx.Fields
	grbuild.label = manga.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MangaID string `json:"MangaID,omitempty"`
//	}
//
//	client.Manga.Query().
//		Select(manga.FieldMangaID).
//		Scan(ctx, &v)
func (mq *MangaQuery) Select(fields ...string) *MangaSelect {
	mq.ctx.Fields = append(mq.ctx.Fields, fields...)
	sbuild := &MangaSelect{MangaQuery: mq}
	sbuild.label = manga.Label
	sbuild.flds, sbuild.scan = &mq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MangaSelect configured with the given aggregations.
func (mq *MangaQuery) Aggregate(fns ...AggregateFunc) *MangaSelect {
	return mq.Select().Aggregate(fns...)
}

func (mq *MangaQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mq); err != nil {
				return err
			}
		}
	}
	for _, f := range mq.ctx.Fields {
		if !manga.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mq.path != nil {
		prev, err := mq.path(ctx)
		if err != nil {
			return err
		}
		mq.sql = prev
	}
	return nil
}

func (mq *MangaQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Manga, error) {
	var (
		nodes       = []*Manga{}
		_spec       = mq.querySpec()
		loadedTypes = [1]bool{
			mq.withChapters != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Manga).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Manga{config: mq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := mq.withChapters; query != nil {
		if err := mq.loadChapters(ctx, query, nodes,
			func(n *Manga) { n.Edges.Chapters = []*Chapter{} },
			func(n *Manga, e *Chapter) { n.Edges.Chapters = append(n.Edges.Chapters, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (mq *MangaQuery) loadChapters(ctx context.Context, query *ChapterQuery, nodes []*Manga, init func(*Manga), assign func(*Manga, *Chapter)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Manga)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Chapter(func(s *sql.Selector) {
		s.Where(sql.InValues(manga.ChaptersColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.manga_chapters
		if fk == nil {
			return fmt.Errorf(`foreign-key "manga_chapters" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "manga_chapters" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (mq *MangaQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mq.querySpec()
	_spec.Node.Columns = mq.ctx.Fields
	if len(mq.ctx.Fields) > 0 {
		_spec.Unique = mq.ctx.Unique != nil && *mq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mq.driver, _spec)
}

func (mq *MangaQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(manga.Table, manga.Columns, sqlgraph.NewFieldSpec(manga.FieldID, field.TypeInt))
	_spec.From = mq.sql
	if unique := mq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mq.path != nil {
		_spec.Unique = true
	}
	if fields := mq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, manga.FieldID)
		for i := range fields {
			if fields[i] != manga.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mq *MangaQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mq.driver.Dialect())
	t1 := builder.Table(manga.Table)
	columns := mq.ctx.Fields
	if len(columns) == 0 {
		columns = manga.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mq.sql != nil {
		selector = mq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mq.ctx.Unique != nil && *mq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mq.predicates {
		p(selector)
	}
	for _, p := range mq.order {
		p(selector)
	}
	if offset := mq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MangaGroupBy is the group-by builder for Manga entities.
type MangaGroupBy struct {
	selector
	build *MangaQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mgb *MangaGroupBy) Aggregate(fns ...AggregateFunc) *MangaGroupBy {
	mgb.fns = append(mgb.fns, fns...)
	return mgb
}

// Scan applies the selector query and scans the result into the given value.
func (mgb *MangaGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mgb.build.ctx, "GroupBy")
	if err := mgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MangaQuery, *MangaGroupBy](ctx, mgb.build, mgb, mgb.build.inters, v)
}

func (mgb *MangaGroupBy) sqlScan(ctx context.Context, root *MangaQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mgb.fns))
	for _, fn := range mgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mgb.flds)+len(mgb.fns))
		for _, f := range *mgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MangaSelect is the builder for selecting fields of Manga entities.
type MangaSelect struct {
	*MangaQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ms *MangaSelect) Aggregate(fns ...AggregateFunc) *MangaSelect {
	ms.fns = append(ms.fns, fns...)
	return ms
}

// Scan applies the selector query and scans the result into the given value.
func (ms *MangaSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ms.ctx, "Select")
	if err := ms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MangaQuery, *MangaSelect](ctx, ms.MangaQuery, ms, ms.inters, v)
}

func (ms *MangaSelect) sqlScan(ctx context.Context, root *MangaQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ms.fns))
	for _, fn := range ms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
