// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mangathrV2/ent/chapter"
	"mangathrV2/ent/manga"
	"mangathrV2/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MangaUpdate is the builder for updating Manga entities.
type MangaUpdate struct {
	config
	hooks    []Hook
	mutation *MangaMutation
}

// Where appends a list predicates to the MangaUpdate builder.
func (mu *MangaUpdate) Where(ps ...predicate.Manga) *MangaUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetMangaID sets the "MangaID" field.
func (mu *MangaUpdate) SetMangaID(s string) *MangaUpdate {
	mu.mutation.SetMangaID(s)
	return mu
}

// SetSource sets the "Source" field.
func (mu *MangaUpdate) SetSource(s string) *MangaUpdate {
	mu.mutation.SetSource(s)
	return mu
}

// SetTitle sets the "Title" field.
func (mu *MangaUpdate) SetTitle(s string) *MangaUpdate {
	mu.mutation.SetTitle(s)
	return mu
}

// SetMapping sets the "Mapping" field.
func (mu *MangaUpdate) SetMapping(s string) *MangaUpdate {
	mu.mutation.SetMapping(s)
	return mu
}

// SetRegisteredOn sets the "RegisteredOn" field.
func (mu *MangaUpdate) SetRegisteredOn(t time.Time) *MangaUpdate {
	mu.mutation.SetRegisteredOn(t)
	return mu
}

// SetFilteredGroups sets the "FilteredGroups" field.
func (mu *MangaUpdate) SetFilteredGroups(s []string) *MangaUpdate {
	mu.mutation.SetFilteredGroups(s)
	return mu
}

// AddChapterIDs adds the "Chapters" edge to the Chapter entity by IDs.
func (mu *MangaUpdate) AddChapterIDs(ids ...int) *MangaUpdate {
	mu.mutation.AddChapterIDs(ids...)
	return mu
}

// AddChapters adds the "Chapters" edges to the Chapter entity.
func (mu *MangaUpdate) AddChapters(c ...*Chapter) *MangaUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return mu.AddChapterIDs(ids...)
}

// Mutation returns the MangaMutation object of the builder.
func (mu *MangaUpdate) Mutation() *MangaMutation {
	return mu.mutation
}

// ClearChapters clears all "Chapters" edges to the Chapter entity.
func (mu *MangaUpdate) ClearChapters() *MangaUpdate {
	mu.mutation.ClearChapters()
	return mu
}

// RemoveChapterIDs removes the "Chapters" edge to Chapter entities by IDs.
func (mu *MangaUpdate) RemoveChapterIDs(ids ...int) *MangaUpdate {
	mu.mutation.RemoveChapterIDs(ids...)
	return mu
}

// RemoveChapters removes "Chapters" edges to Chapter entities.
func (mu *MangaUpdate) RemoveChapters(c ...*Chapter) *MangaUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return mu.RemoveChapterIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MangaUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(mu.hooks) == 0 {
		affected, err = mu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MangaMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mu.mutation = mutation
			affected, err = mu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mu.hooks) - 1; i >= 0; i-- {
			if mu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MangaUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MangaUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MangaUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (mu *MangaUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   manga.Table,
			Columns: manga.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: manga.FieldID,
			},
		},
	}
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.MangaID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: manga.FieldMangaID,
		})
	}
	if value, ok := mu.mutation.Source(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: manga.FieldSource,
		})
	}
	if value, ok := mu.mutation.Title(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: manga.FieldTitle,
		})
	}
	if value, ok := mu.mutation.Mapping(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: manga.FieldMapping,
		})
	}
	if value, ok := mu.mutation.RegisteredOn(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: manga.FieldRegisteredOn,
		})
	}
	if value, ok := mu.mutation.FilteredGroups(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: manga.FieldFilteredGroups,
		})
	}
	if mu.mutation.ChaptersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   manga.ChaptersTable,
			Columns: []string{manga.ChaptersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: chapter.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.RemovedChaptersIDs(); len(nodes) > 0 && !mu.mutation.ChaptersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   manga.ChaptersTable,
			Columns: []string{manga.ChaptersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: chapter.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.ChaptersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   manga.ChaptersTable,
			Columns: []string{manga.ChaptersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: chapter.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{manga.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// MangaUpdateOne is the builder for updating a single Manga entity.
type MangaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MangaMutation
}

// SetMangaID sets the "MangaID" field.
func (muo *MangaUpdateOne) SetMangaID(s string) *MangaUpdateOne {
	muo.mutation.SetMangaID(s)
	return muo
}

// SetSource sets the "Source" field.
func (muo *MangaUpdateOne) SetSource(s string) *MangaUpdateOne {
	muo.mutation.SetSource(s)
	return muo
}

// SetTitle sets the "Title" field.
func (muo *MangaUpdateOne) SetTitle(s string) *MangaUpdateOne {
	muo.mutation.SetTitle(s)
	return muo
}

// SetMapping sets the "Mapping" field.
func (muo *MangaUpdateOne) SetMapping(s string) *MangaUpdateOne {
	muo.mutation.SetMapping(s)
	return muo
}

// SetRegisteredOn sets the "RegisteredOn" field.
func (muo *MangaUpdateOne) SetRegisteredOn(t time.Time) *MangaUpdateOne {
	muo.mutation.SetRegisteredOn(t)
	return muo
}

// SetFilteredGroups sets the "FilteredGroups" field.
func (muo *MangaUpdateOne) SetFilteredGroups(s []string) *MangaUpdateOne {
	muo.mutation.SetFilteredGroups(s)
	return muo
}

// AddChapterIDs adds the "Chapters" edge to the Chapter entity by IDs.
func (muo *MangaUpdateOne) AddChapterIDs(ids ...int) *MangaUpdateOne {
	muo.mutation.AddChapterIDs(ids...)
	return muo
}

// AddChapters adds the "Chapters" edges to the Chapter entity.
func (muo *MangaUpdateOne) AddChapters(c ...*Chapter) *MangaUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return muo.AddChapterIDs(ids...)
}

// Mutation returns the MangaMutation object of the builder.
func (muo *MangaUpdateOne) Mutation() *MangaMutation {
	return muo.mutation
}

// ClearChapters clears all "Chapters" edges to the Chapter entity.
func (muo *MangaUpdateOne) ClearChapters() *MangaUpdateOne {
	muo.mutation.ClearChapters()
	return muo
}

// RemoveChapterIDs removes the "Chapters" edge to Chapter entities by IDs.
func (muo *MangaUpdateOne) RemoveChapterIDs(ids ...int) *MangaUpdateOne {
	muo.mutation.RemoveChapterIDs(ids...)
	return muo
}

// RemoveChapters removes "Chapters" edges to Chapter entities.
func (muo *MangaUpdateOne) RemoveChapters(c ...*Chapter) *MangaUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return muo.RemoveChapterIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MangaUpdateOne) Select(field string, fields ...string) *MangaUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Manga entity.
func (muo *MangaUpdateOne) Save(ctx context.Context) (*Manga, error) {
	var (
		err  error
		node *Manga
	)
	if len(muo.hooks) == 0 {
		node, err = muo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MangaMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			muo.mutation = mutation
			node, err = muo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(muo.hooks) - 1; i >= 0; i-- {
			if muo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = muo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, muo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MangaUpdateOne) SaveX(ctx context.Context) *Manga {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MangaUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MangaUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (muo *MangaUpdateOne) sqlSave(ctx context.Context) (_node *Manga, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   manga.Table,
			Columns: manga.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: manga.FieldID,
			},
		},
	}
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Manga.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, manga.FieldID)
		for _, f := range fields {
			if !manga.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != manga.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.MangaID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: manga.FieldMangaID,
		})
	}
	if value, ok := muo.mutation.Source(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: manga.FieldSource,
		})
	}
	if value, ok := muo.mutation.Title(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: manga.FieldTitle,
		})
	}
	if value, ok := muo.mutation.Mapping(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: manga.FieldMapping,
		})
	}
	if value, ok := muo.mutation.RegisteredOn(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: manga.FieldRegisteredOn,
		})
	}
	if value, ok := muo.mutation.FilteredGroups(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: manga.FieldFilteredGroups,
		})
	}
	if muo.mutation.ChaptersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   manga.ChaptersTable,
			Columns: []string{manga.ChaptersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: chapter.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.RemovedChaptersIDs(); len(nodes) > 0 && !muo.mutation.ChaptersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   manga.ChaptersTable,
			Columns: []string{manga.ChaptersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: chapter.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.ChaptersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   manga.ChaptersTable,
			Columns: []string{manga.ChaptersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: chapter.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Manga{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{manga.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
