name: Go build & publish
permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags: [ 'v*.*.*' ]   # Publish semver tags as releases.
    paths-ignore:
      - "docs/**"
      - ".github/**"
      - ".idea/**"
      - "examples/**"
      - "*.md"
      - ".gitignore"

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go 1.23.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - name: Cross-compile Go programs
        run: |
          set -eu -o pipefail
          
          make cross-build VERSION="${{ github.ref_name }}"
          make dist VERSION="${{ github.ref_name }}"

      - name: Upload archives to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: dist/*.{zip,tar.gz}
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
