// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Chapter is the predicate function for chapter builders.
type Chapter func(*sql.Selector)

// Manga is the predicate function for manga builders.
type Manga func(*sql.Selector)
